version: '3.9'

services:
    backend:
        build: .
        container_name: chat-app-backend
        restart: always
        ports:
            - '7000:7000'
        env_file:
            - .env
        depends_on:
            - postgres
    # no-need: already created
    # redis:
    #     image: redis:7
    #     container_name: redis
    #     restart: always
    #     ports:
    #         - '6379:6379'

    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123321tharhtetmin
            POSTGRES_DB: kqioieaermstzmoxpias
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
